- name: Check for site's certificate duration
  hosts: localhost
  vars:
    # Override with your own site list
    sites:
      - google.com
      - yahoo.com
      - azure.com
      - example.com
    # We will make use of the current date in unix epoch
    # ansible_facts.date_time.epoch

  tasks:
    - name: Use openssl to check cert's validity
      ansible.builtin.shell:
        cmd: >-
          set -o pipefail &&
          echo |
          openssl s_client -servername {{ item }} -connect {{ item }}:443 2>/dev/null |
          openssl x509 -noout -enddate |
          cut -d= -f2 |
          xargs -I {} date -u -d "{}" +%s
        executable: /bin/bash
      changed_when: false
      loop: "{{ sites }}"
      register: validity_output

    - name: Show raw results
      ansible.builtin.debug:
        var: validity_output
        verbosity: 2

    - name: Combine time output into a usable list
      ansible.builtin.set_fact:
        ssl_results: >-
          {{
          (ssl_results | default([])) +
          [
          {
            'hostname': sites[ansible_loop.index0],
            'notAfter': item.stdout,
            'remainingSeconds': item.stdout | int - ansible_facts.date_time.epoch | int
          }
          ]
          }}
      loop: "{{ validity_output.results }}"
      loop_control:
        extended: true

    - name: Show list of endpoints with their remaining life
      ansible.builtin.debug:
        var: ssl_results
